### ISSUE TITLE
Feature request: Javascript link checking

### ISSUE THREAD

**Issue by andymule** [wjdp/htmltest#110]
Would be great if htmltest also crawled js code and link checked its contents

**Comment by wjdp** [comment]
Hmm, interesting idea.

Been thinking about this really the only way of this working would be to grep through source code looking for things that look like links and checking those. There's many many ways you could store a link in JS, it's not like html at all where links are only on preset elements.

This though does not solve half the issues html usually catches, when things that should be links don't look like links anymore.

Secondly to this htmltest is usually run on sites that have come out of some generation process. JS normally isn't generated. (If it's transpiled this process largely does not introduce errors).

Thirdly I would imagine we would run across false positives which is something I really don't want.

On reflection this seems to be a feature best suited for another tool. I think if we tried this it wouldn't ever be feature complete or even work very well.

I'm going to close this issue for now. If there is more interest and a clear path forward we can discuss.
