### ISSUE TITLE
OutputLogFile does not populate logfile using .htmltest

### ISSUE THREAD

**Issue by Merovex** [wjdp/htmltest#116]
The feature `OutputLogFile` does not populate when using the .htmltest feature

```
DirectoryPath: "public"
EnforceHTTPS: true
CacheExpires: "6h"
OutputLogFile: htmltest.log
LogLevel: 3
IgnoreAltMissing: false
CheckInternal: false
```

**Comment by wjdp** [comment]
Hi @Merovex, using the above config you will find the log file at `tmp/.htmltest/htmltest.log`. If you want this file written elsewhere please look at the `OutputDir` config parameter.

**Comment by Merovex** [comment]
I found it. Is this in the documentation, or is it missing from the docs?

**Comment by wjdp** [comment]
It's in the config section of the README
