### ISSUE TITLE
Skip TLS verify option

### ISSUE THREAD

**Issue by xadcoh** [wjdp/htmltest#123]
Hi It's not a bug it's a feature request.

Could you please consider to add `--skip-tls-verification` option

You could do it with conditional against transport var (and add `TLSClientConfig: &tls.Config{InsecureSkipVerify: true},`):
```
	transport := &http.Transport{
		// Disable HTTP/2, this is required due to a number of edge cases where http negotiates H2, but something goes
		// wrong when actually using it. Downgrading to H1 when this issue is hit is not yet supported so we use the
		// following to disable H2 support:
		// > Programs that must disable HTTP/2 can do so by setting Transport.TLSNextProto ... to a non-nil, empty map.
		// See issue #49
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		TLSNextProto:    make(map[string]func(authority string, c *tls.Conn) http.RoundTripper),
	}
```

**Comment by wjdp** [comment]
Hi, this makes sense and should def be a config option.

**Comment by jgazeau** [comment]
@xadcoh , @wjdp . You can check what I have done in this PR. I think it match your needs.

**Comment by wjdp** [comment]
@xadcoh @jgazeau Apologies, had my head of this project for a while. jgazeau's PR #113 should cover what's being asked for here. This is now merged on master.

@xadcoh You should find a build on here soon to try it out https://builds.htmltest.wjdp.uk/

**Comment by jgazeau** [comment]
@wjdp No problems 😉
