### ISSUE TITLE
Question about OutputDir

### ISSUE THREAD

**Issue by g1eny0ung** [wjdp/htmltest#128]
@wjdp Thanks u very much for developing htmltest, it's very useful.

And I have a little question about `OutputDir`, this is my configuration:

```yml
OutputDir: ~/.htmltest
```

I want to output the results to my `$HOME`, but its output in my current repo folder:

![image](https://user-images.githubusercontent.com/15034155/65096361-518f3500-d9f7-11e9-9913-7a7b0e9b314f.png)

How can I ouput it to `$HOME`? Thanks for the reply.

**Comment by wjdp** [comment]
Hey @g1eny0ung,

I don't think there's an easy way to get htmltest to write to your `$HOME` as, after joining, we're passing the paths from the config direct to go's `WriteFile` method (https://golang.org/pkg/io/ioutil/#WriteFile) which likely won't support environment variables.

A workaround to get what you want may be just to create a symlink in your current directory to your home dir. e.g. set `OutputDir: .htmltest` and

```bash
# ensure directory exists in home
mkdir -p ~/.htmltest
# symlink the home directory to our current directory
ln -s ~/.htmltest .htmltest
# run htmltest
htmltest
```

**Comment by g1eny0ung** [comment]
Thanks for explaining! Because I want to use docker to keep the cache dir for the next usage. Seems that I can move the folder to the persistent storage and move back for the next usage.
