### ISSUE TITLE
Support installation on OpenBSD/amd64

### ISSUE THREAD

**Issue by leonstafford** [wjdp/htmltest#141]
Unable to install on OpenBSD

Add support for installation on OpenBSD, `doas` v `sudo`, `ksh` over `bash`

Haven't looked into what is required for PR yet

**Comment by wjdp** [comment]
I have zero experience with BSD, would appreciate some help here.

**Comment by leonstafford** [comment]
@wjdp happy to help! Wanted to get the feature request in at least. I have zero experience with Go, but should be able to do some prep/maybe a PR. 

Thinking out loud:

 - [ ] see what errors occur when the platform check is removed
 - [ ] check for `sudo` calls, see how other projects have added `doas` support
 - [ ] check for `bash` usage, see if it can change to `sh` or detect/switch if no `bash`, but have `ksh`
 - [ ] see if there's a way to add OpenBSD tests to current CI

**Comment by leonstafford** [comment]
Checking out source allows it to build and execute fine for me on `-current` version of OpenBSD. 

So, will check what can be done to the docs / public install script currently failing

**Comment by leonstafford** [comment]
public install script generated by https://github.com/goreleaser/godownloader, no longer actively maintained, but has some activity in repo. 

If contributing upstream to godownloader doesn't make sense, can look to patch current generated installer script to support OpenBSD
 
[Caddy installer script](https://getcaddy.com) for reference supporting OpenBSD

**Comment by leonstafford** [comment]
alternatively, add notes in docs for installation on OpenBSD:

 - build from source (just `go` dependency)
 - alternative copy pasta install command using `ftp`
 - `go get` possible?

**Comment by leonstafford** [comment]
may also be able to adjust `goreleaser` usage to build release for OpenBSD, similar to recommended install steps for Windows

**Comment by wjdp** [comment]
Have merged the MR but not on a machine where I can tag a new release today. Should be able to soon.

**Comment by wjdp** [comment]
Hi @leonstafford. Release is done, can you pull one of the binaries and check it works on your machine?

https://github.com/wjdp/htmltest/releases/tag/v0.12.1

**Comment by leonstafford** [comment]
@wjdp many thanks! Working well here (amd64) 😸
