### ISSUE TITLE
TestAnchorExternalHrefIPTimeout is flaky

### ISSUE THREAD

**Issue by QuLogic** [wjdp/htmltest#148]
# Describe the bug
We're trying to rebuild with Go 1.15, but I keep running into issues with `TestAnchorExternalHrefIPTimeout`. 

# To Reproduce
1. `go test github.com/wjdp/htmltest/htmltest`

# Expected behaviour
Tests work.

# Actual behaviour
This randomly fails. Here are [the](https://koji.fedoraproject.org/koji/taskinfo?taskID=47981883) [last](https://koji.fedoraproject.org/koji/taskinfo?taskID=48334441) [four](https://koji.fedoraproject.org/koji/taskinfo?taskID=48413328) [attempts](https://koji.fedoraproject.org/koji/taskinfo?taskID=48413857). As you can see, it fails on different systems every time.

The failure is always the same, though:
```
github.com/wjdp/htmltest/htmltest
<<<<<<<<<<<<<<<<<<<<<<<<
testDocument on ip_timeout.html
fresh --- ip_timeout.html --> http://5.6.7.8
hitting --- ip_timeout.html --> http://5.6.7.8
Get "http://5.6.7.8": dial tcp 5.6.7.8:80: i/o timeout (Client.Timeout exceeded while awaiting headers) --- ip_timeout.html --> http://5.6.7.8
>>>>>>>>>>>>>>>>>>>>>>>>
--- FAIL: TestAnchorExternalHrefIPTimeout (1.00s)
    test_helpers_test.go:23: expected issue request exceeded our ExternalTimeout count 1 != 0
FAIL
```
It seems to be timing out, but raising a slightly different error.

## Versions
 - OS: Fedora Rawhide
 - htmltest: 0.12.1

**Comment by wjdp** [comment]
Hey @QuLogic, sorry for the delay! 

I can't see anything obvious here. The expected issue is triggered by `Client.Timeout` being present in the underlying HTTP error, which in the log it is??

We should be running against 1.15 soon, am doing so locally already, so will see if this is reproduced.

**Comment by wjdp** [comment]
Aaand while playing around with Go 1.15 on GitHub actions I see this on an Ubuntu 10.04 runner

```
=== RUN   TestAnchorExternalHrefIPTimeout
<<<<<<<<<<<<<<<<<<<<<<<<
testDocument on ip_timeout.html
fresh --- ip_timeout.html --> http://5.6.7.8
hitting --- ip_timeout.html --> http://5.6.7.8
Get "http://5.6.7.8": dial tcp 5.6.7.8:80: i/o timeout (Client.Timeout exceeded while awaiting headers) --- ip_timeout.html --> http://5.6.7.8
>>>>>>>>>>>>>>>>>>>>>>>>
```
