### ISSUE TITLE
Anchors in `pre` tags are raising errors.

### ISSUE THREAD

**Issue by themr0c** [wjdp/htmltest#163]
# Describe the bug

Anchors in `pre` tags are raising errors.

# To Reproduce
Steps to reproduce the behaviour:
1. Run with config and options …
2. Scroll down to '....'
3. See error

### .htmltest.yml

Non impacting.

### Source files

```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE html>

<pre><span id="ABCDE" />1</span></pre>
<a href="#ABCDE">1</a>

<span id="FGHIJ" />2</span>
<a href="#FGHIJ">2</span>
```

# Expected behaviour

No errors (as the second anchornot in a `pre` tag).

# Actual behaviour

```
htmltest test-snippet.html
htmltest started at 08:31:42 on .
========================================================================
test-snippet.html
  hash does not exist --- test-snippet.html --> #ABCDE
========================================================================
✘✘✘ failed in 291.944489ms
1 errors
```

## Versions
 - OS: Fedora 33
 - htmltest: 0.13.0 / 2020-08-12T21:13:49Z

**Comment by wjdp** [comment]
Dug into this, the problem is we are currently ignoring all html inside `pre` and `code` tags. This seems to have been a mistake as HTML is very much valid in these tags.
