### ISSUE TITLE
exceptions for EnforceHTTPS

### ISSUE THREAD

**Issue by kylrth** [wjdp/htmltest#191]
`EnforceHTTPS` has already helped me discover several instances where I point to the HTTP version of an external site when there's a functioning HTTPS version. Unfortunately, a few sites are only available with HTTP, but I don't want to add them to `IgnoreURLs` because I still do want to check them. Can we add a separate exception list for `EnforceHTTPS`?

I'm willing to open a PR but I wanted to run it by you first.

**Comment by wjdp** [comment]
Heya @kylrth! This use case makes a lot of sense, I'd be open to accepting a PR for this.
