### ISSUE TITLE
Support s3 for cache file

### ISSUE THREAD

**Issue by ttripp** [wjdp/htmltest#196]
Running this in a build container.  Can we specify an s3 signed URL instead?

**Comment by wjdp** [comment]
It'd be a nice to have but don't really want to extend the scope of the project to include this. Rather users can just sync an s3 bucket in their CI job before and after running htmltest. Most CI providers offer inbuilt caching functionality sometimes backed by s3.

Gonna close this as rather unlikely this will be picked up.
