### ISSUE TITLE
Move away from godownloader as main recommended way of installing htmltest

### ISSUE THREAD

**Issue by chalin** [wjdp/htmltest#197]
`godownloader` has been deprecated: for details, see https://github.com/goreleaser/godownloader/issues/207. It isn't clear to me what the alternative is, but I wanted to open this issue since `godownloader` is the main recommended way of installing `htmltest`.

**Comment by wjdp** [comment]
It's not much of an issue in the short/medium term as all godownloader does is generate a [shell script](https://github.com/wjdp/htmltest/blob/master/godownloader.sh) which pulls the correct binary for your platform. I'm happy to keep it alongside packages and just grabbing a binary from the releases page.

Will close this for now. If we do see issues with it that can't be easily fixed then it may become time to remove it.
