### ISSUE TITLE
Add Configuration Option to Limit Redirects

### ISSUE THREAD

**Issue by istr** [wjdp/htmltest#204]
When testing for stale / outdated links it is very helpful to fail on redirects.

I propose to add a `RedirectLimit` option (as `int` value) with the following semantics

- unset or negative value: use the default limit built into net/http
- positive value: limit allowed number of redirects

Setting this to `0` would result in a failure for redirected links.

I will prepare a PR for this shortly.

**Comment by wjdp** [comment]
Implemented in #205
