### ISSUE TITLE
Checking any URL that appears in the text even if it's not an HTML link

### ISSUE THREAD

**Issue by bennythejudge** [wjdp/htmltest#46]
A colleague noticed that any URL that appears in the text (unless enclosed between backticks - one or more), will be checked for being a valid link - unless it's added to the `IgnoreURLs` list in `.htmltest.yml`.
I was expecting that only the URLs in links would be checked.
Would it make sense to have a parameter for such behavior so that htmltest is not checking any URL that appears in the text?
Thanks for making htmltest!

**Comment by wjdp** [comment]
This shouldn't happen. Can you provide a single HTML file that reproduces this problem?

**Comment by bennythejudge** [comment]
Please ignore.
I just realized that hugo (or blackfriday?) is converting the URL into a link even if it has not markdown markers for a link
My apologies I should have looked better.
