### ISSUE TITLE
Link to "index.html" generates "href lacks trailing slash" error

### ISSUE THREAD

**Issue by slawo-ch** [wjdp/htmltest#55]
I have a site linking to `index.html` instead of `/`. It makes it possible to browse the site from the file system.

Htmltest seems to want a trailing slash on such links, even though they are perfectly good links to existing html pages.

**Comment by wjdp** [comment]
Hi @slawo-ch, thanks for the report. I can reproduce this and will address in the linked PR in due course.

Rather basic issue, only minorly embarrassing :sweat_smile:!

**Comment by wjdp** [comment]
In the meantime you can add `IgnoreDirectoryMissingTrailingSlash: True` to your config to skip this erroneous check.

**Comment by slawo-ch** [comment]
Thanks @wjdp! Your work on this is much appreciated. The workaround works for me.
