### ISSUE TITLE
Add option to set user agent

### ISSUE THREAD

**Issue by vokal-isaac** [wjdp/htmltest#67]
I have encountered some instances where the default net/http user agent string causes a server to return a 403 or 503 error.  It would be useful to be able to set a custom user agent in the configuration.

It might also be nice for the default to be something like `htmltest/X.X.X` instead of the net/http default.

**Comment by wjdp** [comment]
Agree on both counts.

- Default user agent should have `htmltest/x.x.x` in it. I'm no expert on UAs but there is some history with them we'll need to keep in mind (usually need to have 'Mozilla compatible' in it)
- Add a config option to set a manual UA

**Comment by vokal-isaac** [comment]
I took a quick stab at trying to implement this myself, but I haven't worked on a go-based app before and none of the things I changed seemed to affect the binary that resulted from running `build.sh`, so I think I'm missing a step somewhere in the setup or build process.
