### ISSUE TITLE
Send Accept header (or add an option to send it)

### ISSUE THREAD

**Issue by vokal-isaac** [wjdp/htmltest#68]
I have encountered at least one URL that yields a 403 error when htmltest checks it, but if I add an `Accept: */*` header to the request, it succeeds.  It might be useful to have an Accept header by default, but at least having an option to add one would help.

**Comment by wjdp** [comment]
Unsure what it should be set to, what do normal browser send?

Config option would be valuable.

**Comment by vokal-isaac** [comment]
For reference, this yields a 403:
```sh
curl -Ls \
    -H "User-Agent: Go-http-client/1.1" \
    -H "Range: bytes=0-0" \
    -H "Accept:" \
    -o /dev/null \
    -w "%{http_code}\n" \
    'http://html5doctor.com/'
```
whereas this yields a 200:
```sh
curl -Ls \
    -H "User-Agent: Go-http-client/1.1" \
    -H "Range: bytes=0-0" \
    -H "Accept: */*" \
    -o /dev/null \
    -w "%{http_code}\n" \
    'http://html5doctor.com/'
```

**Comment by wjdp** [comment]
Just done a bit of reading into what browsers send. Seems to be a preference list that varies in levels of sensibility between vendors and all end with `*/*`. I will look into making that the default here.
