### ISSUE TITLE
Add an option to ignore blank href

### ISSUE THREAD

**Issue by seisman** [wjdp/htmltest#86]
htmltest reports errors when a href is blank. For example, the internal pagination template of hugo generates some codes like `<a href="" aria-label="Previous"><span aria-hidden="true">«</span></a>`.

Is it possible to add an option to add an option to ignore errors like this?

**Comment by seisman** [comment]
@wjdp Thanks for your quick reply. 

Adding `data-proofer-ignore` is not an option for me, since codes like this are generated by internal template of hugo. I have no control with the internal template, unless totally overwrite it. 

Maybe an option `CheckEmptyHref` (default to `true`) or `IgnoreEmptyHref` (default to `false`) is better?

**Comment by divinerites** [comment]
Update on this use case (also linked to gohugo.io internal paginator template. And exact same HTML code.

I still have `href blank` errors even with those options :

```yaml
CheckAnchors: true
IgnoreEmptyHref: true
IgnoreInternalEmptyHash: true
```

To me the `IgnoreEmptyHref` is made for this exact use case, but fails. No ?

**Comment by divinerites** [comment]
And looking at https://github.com/wjdp/htmltest/pull/106/files it seems that this `IgnoreEmptyHref` was a WIP `IgnoreBlankHref `.

So what is the state of `IgnoreEmptyHref ` ?? Working ? Only on docs ?

Thanks a LOT for any information about that.
htmltest is such a great valuable tool !! I use it everyday ...

**Comment by divinerites** [comment]
On a side note, and **for gohugo.io users**, this problem will be solved in the next hugo version with this commit : https://github.com/gohugoio/hugo/commit/88c8a15be18a0bd1bd9b9cb175f7a68f2b9cd355

**Comment by wjdp** [comment]
`IgnoreEmptyHref` on the README is a new feature not yet released. It seems a release is due, will sort that out shortly. You can check the docs for the currently released version by picking the correct tag on the dropdown top left:

![image](https://user-images.githubusercontent.com/1690934/60969684-0a5e3700-a318-11e9-8420-5f166c72f3e3.png)

**Comment by wjdp** [comment]
Option exists and will be released shortly, closing now.
