### ISSUE TITLE
List (only) external links

### ISSUE THREAD

**Issue by skyzyx** [wjdp/htmltest#91]
I'm interested in _finding_ external links in my 15 years of blog history.

Not checking for validity. Not validating anything. Just _listing_.

Is there a way to do this?

**Comment by wjdp** [comment]
We do extract these links from your files but don't store them after they're validated. If we implemented a stats/reports system this may be added through that.

**Comment by wjdp** [comment]
Closing this for now. Can re-open if there is more appetite / interest.
