### ISSUE TITLE
Allow ignore tags in parent HTML tags too

### ISSUE THREAD

**Issue by kaushalmodi** [wjdp/htmltest#95]
Putting `data-proofer-ignore="true"` in `<a ..>` tags works great!

Though, I have come across use cases where's it's not possible to know before-hand if an a tag will have a non-https link (like links fetched through webmentions). But I know for sure that these links will reside in a set `<div ..>`.

So, if I have:

```html
<div data-proofer-ignore="true">
  <a href="http://example.com">Non-secure link</a>
</div>
```

Can you add an option so that the above method also results in `htmltest` PASS with `EnforceHTTPS: true`?

**Comment by wjdp** [comment]
Very good idea, we should do this!

**Comment by kaushalmodi** [comment]
Awesome! Thank you. I confirm that this new feature works!
